FROM node:20-bullseye

RUN apt-get update && apt-get install -y sudo && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && usermod -aG sudo node \
    && echo "node ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN mkdir -p /workspace && chown -R node:node /workspace

USER node